#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="${SERVICE_NAME:-insuredbylena-portal-api}"
REGION="${REGION:-us-central1}"
PROJECT_ID="${PROJECT_ID:-}"
RUN_SMOKE_TEST="${RUN_SMOKE_TEST:-1}"
RUN_BACKEND_REGRESSION="${RUN_BACKEND_REGRESSION:-1}"

if [[ -z "$PROJECT_ID" ]]; then
  echo "PROJECT_ID is required"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_DIR="${SCRIPT_DIR}/../tests"

gcloud run deploy "$SERVICE_NAME" \
  --project "$PROJECT_ID" \
  --region "$REGION" \
  --source "$SCRIPT_DIR" \
  --set-env-vars "SUPABASE_URL=${SUPABASE_URL:-},SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-},GOOGLE_CALENDAR_WEB_APP_URL=${GOOGLE_CALENDAR_WEB_APP_URL:-},GOOGLE_CALENDAR_SECRET=${GOOGLE_CALENDAR_SECRET:-},CONTENT_PUBLISHER_MODE=${CONTENT_PUBLISHER_MODE:-},BUFFER_API_KEY=${BUFFER_API_KEY:-},BUFFER_ORGANIZATION_ID=${BUFFER_ORGANIZATION_ID:-},BUFFER_CHANNEL_ID_INSTAGRAM=${BUFFER_CHANNEL_ID_INSTAGRAM:-},BUFFER_CHANNEL_ID_FACEBOOK=${BUFFER_CHANNEL_ID_FACEBOOK:-},BUFFER_CHANNEL_ID_TIKTOK=${BUFFER_CHANNEL_ID_TIKTOK:-},BUFFER_API_BASE_URL=${BUFFER_API_BASE_URL:-},CONTENT_SCHEDULER_WEBHOOK_URL=${CONTENT_SCHEDULER_WEBHOOK_URL:-},CONTENT_SCHEDULER_API_KEY=${CONTENT_SCHEDULER_API_KEY:-},CONTENT_SCHEDULER_NAME=${CONTENT_SCHEDULER_NAME:-}" \
  --allow-unauthenticated

if [[ "$RUN_SMOKE_TEST" == "1" ]]; then
  echo "Running portal smoke test..."
  python3 "${TEST_DIR}/smoke_portal.py"
fi

if [[ "$RUN_BACKEND_REGRESSION" == "1" ]]; then
  echo "Running backend regression test..."
  python3 "${TEST_DIR}/backend_regression.py"
fi
