create table if not exists public.error_event (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  service_name text not null default 'insuredbylena-portal-api',
  request_id text not null,
  method text not null,
  route text not null,
  status integer not null,
  error_code text not null,
  message text not null,
  details_json jsonb not null default '{}'::jsonb
);

create index if not exists idx_error_event_occurred_at
  on public.error_event (occurred_at desc);

create index if not exists idx_error_event_status
  on public.error_event (status, occurred_at desc);

create index if not exists idx_error_event_route
  on public.error_event (route, occurred_at desc);

create index if not exists idx_error_event_request_id
  on public.error_event (request_id);

alter table public.error_event enable row level security;

drop policy if exists "admin full error event access" on public.error_event;

create policy "admin full error event access"
on public.error_event
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
