create table if not exists public.lead_document (
  document_id bigint generated by default as identity primary key,
  lead_id bigint not null references public.lead_master(lead_id) on delete cascade,
  source_kind text not null default 'upload',
  document_category text not null default 'general',
  file_name text not null,
  storage_bucket text,
  storage_path text,
  source_url text,
  mime_type text,
  file_size_bytes bigint,
  notes text,
  uploaded_by_email text,
  archived_at timestamptz,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_lead_document_lead_id
  on public.lead_document (lead_id, inserted_at desc);

create index if not exists idx_lead_document_active
  on public.lead_document (archived_at, document_category);

drop trigger if exists trg_lead_document_touch_updated_at on public.lead_document;
create trigger trg_lead_document_touch_updated_at
before update on public.lead_document
for each row execute function public.touch_updated_at();

alter table public.lead_document enable row level security;

drop policy if exists "admin full lead document access" on public.lead_document;

create policy "admin full lead document access"
on public.lead_document
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
