create table if not exists public.maintenance_audit_log (
  id bigint generated by default as identity primary key,
  action_type text not null,
  actor_email text,
  details_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_maintenance_audit_log_created_at
  on public.maintenance_audit_log (created_at desc);

create index if not exists idx_maintenance_audit_log_action_type
  on public.maintenance_audit_log (action_type);

alter table public.maintenance_audit_log enable row level security;

drop policy if exists "admin full maintenance audit access" on public.maintenance_audit_log;
create policy "admin full maintenance audit access"
on public.maintenance_audit_log
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
