create table if not exists public.public_intake_submission (
  id bigint generated by default as identity primary key,
  source text not null,
  full_name text,
  email text,
  phone text,
  coverage_need text,
  preferred_time text,
  message text,
  lead_id bigint references public.lead_master(lead_id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.public_intake_submission enable row level security;

drop policy if exists "admin full intake submission access" on public.public_intake_submission;
create policy "admin full intake submission access"
on public.public_intake_submission
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create or replace function public.public_submit_intake(
  p_source text,
  p_full_name text,
  p_email text default null,
  p_phone text default null,
  p_coverage_need text default null,
  p_preferred_time text default null,
  p_message text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_first_name text;
  v_last_name text;
  v_clean_name text := trim(coalesce(p_full_name, ''));
  v_clean_email text := lower(trim(coalesce(p_email, '')));
  v_clean_phone text := trim(coalesce(p_phone, ''));
  v_clean_source text := trim(coalesce(p_source, 'website'));
  v_clean_need text := trim(coalesce(p_coverage_need, ''));
  v_notes text;
  v_product_line text;
  v_lead_id bigint;
  v_lead_external_id text := 'WEB-' || upper(substring(encode(gen_random_bytes(6), 'hex') from 1 for 12));
begin
  if v_clean_name = '' then
    raise exception 'Full name is required';
  end if;

  if v_clean_email = '' and v_clean_phone = '' then
    raise exception 'Email or phone is required';
  end if;

  v_first_name := split_part(v_clean_name, ' ', 1);
  if strpos(v_clean_name, ' ') > 0 then
    v_last_name := btrim(substr(v_clean_name, length(v_first_name) + 1));
  else
    v_last_name := '';
  end if;

  v_product_line := case
    when lower(v_clean_need) like '%medicare%' then 'Health'
    when lower(v_clean_need) like '%health%' then 'Health'
    when lower(v_clean_need) like '%under 65%' then 'Health'
    when lower(v_clean_need) like '%life%' then 'Life'
    when lower(v_clean_need) like '%team%' or lower(v_clean_source) = 'join_team' then 'Careers'
    else 'Health'
  end;

  v_notes := concat_ws(
    ' | ',
    case when trim(coalesce(p_message, '')) <> '' then 'Message: ' || trim(p_message) else null end,
    case when trim(coalesce(p_preferred_time, '')) <> '' then 'Preferred time: ' || trim(p_preferred_time) else null end
  );

  insert into public.lead_master (
    lead_external_id,
    first_name,
    last_name,
    full_name,
    email,
    mobile_phone,
    lead_source,
    lead_source_detail,
    campaign_name,
    product_interest,
    product_line,
    owner_queue,
    lead_status,
    booking_status,
    consent_status,
    dnc_status,
    contact_eligibility,
    notes,
    routing_bucket,
    recommended_channel,
    sequence_name,
    recommended_next_action,
    priority_tier,
    pipeline_status
  ) values (
    v_lead_external_id,
    v_first_name,
    v_last_name,
    v_clean_name,
    nullif(v_clean_email, ''),
    nullif(v_clean_phone, ''),
    'website',
    v_clean_source,
    case when lower(v_clean_source) = 'join_team' then 'Website Careers Intake' else 'Website Consultation Intake' end,
    nullif(lower(v_clean_need), ''),
    v_product_line,
    'intake_queue',
    'new',
    'not_started',
    'review_required',
    'pending_check',
    'review_required',
    v_notes,
    'intake_queue',
    'manual_review',
    case when lower(v_clean_source) = 'join_team' then 'website_join_team' else 'website_consultation' end,
    case when lower(v_clean_source) = 'join_team' then 'review candidate inquiry and follow up' else 'review coverage request and follow up' end,
    'normal',
    'new'
  )
  returning lead_id into v_lead_id;

  insert into public.public_intake_submission (
    source,
    full_name,
    email,
    phone,
    coverage_need,
    preferred_time,
    message,
    lead_id
  ) values (
    v_clean_source,
    v_clean_name,
    nullif(v_clean_email, ''),
    nullif(v_clean_phone, ''),
    nullif(v_clean_need, ''),
    nullif(trim(coalesce(p_preferred_time, '')), ''),
    nullif(trim(coalesce(p_message, '')), ''),
    v_lead_id
  );

  return jsonb_build_object(
    'ok', true,
    'lead_id', v_lead_id,
    'lead_external_id', v_lead_external_id
  );
end;
$$;

revoke all on function public.public_submit_intake(text, text, text, text, text, text, text) from public;
grant execute on function public.public_submit_intake(text, text, text, text, text, text, text) to anon, authenticated;
