create extension if not exists pgcrypto;

create table if not exists public.app_user_profile (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select p.role
      from public.app_user_profile p
      where p.user_id = auth.uid()
      limit 1
    ),
    ''
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() = 'admin';
$$;

create or replace function public.has_content_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() = any(allowed_roles);
$$;

create or replace function public.can_edit_content()
returns boolean
language sql
stable
as $$
  select public.has_content_role(array['admin', 'editor', 'approver']);
$$;

create or replace function public.can_approve_content()
returns boolean
language sql
stable
as $$
  select public.has_content_role(array['admin', 'approver']);
$$;

create or replace function public.can_publish_content()
returns boolean
language sql
stable
as $$
  select public.has_content_role(array['admin']);
$$;

revoke all on function public.current_app_role() from public;
grant execute on function public.current_app_role() to authenticated;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

revoke all on function public.has_content_role(text[]) from public;
grant execute on function public.has_content_role(text[]) to authenticated;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.lead_master (
  lead_id bigint generated by default as identity primary key,
  lead_external_id text unique,
  first_name text,
  last_name text,
  full_name text,
  email text,
  mobile_phone text,
  business_name text,
  lead_source text,
  lead_source_detail text,
  campaign_name text,
  product_interest text,
  product_line text,
  owner_queue text,
  lead_status text,
  booking_status text,
  consent_status text,
  consent_channel_sms text,
  consent_channel_email text,
  consent_channel_whatsapp text,
  dnc_status text,
  contact_eligibility text,
  created_at_source timestamptz,
  last_activity_at_source timestamptz,
  notes text,
  raw_tags text,
  routing_bucket text,
  suppress_reason text,
  recommended_channel text,
  sequence_name text,
  recommended_next_action text,
  priority_tier text,
  age text,
  tobacco text,
  health_posture text,
  disposition text,
  carrier_match text,
  confidence text,
  pipeline_status text,
  calendar_event_id text,
  next_appointment_time timestamptz,
  last_opened_at timestamptz,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lena_source_profile (
  lena_profile_id bigint generated by default as identity primary key,
  lead_id bigint references public.lead_master(lead_id) on delete set null,
  contact_id text unique not null,
  first_name text,
  last_name text,
  phone text,
  email text,
  business_name text,
  created_at_source timestamptz,
  last_activity_at_source timestamptz,
  tags text,
  notes text,
  source_type text,
  source_platform text,
  source_confidence text,
  source_evidence text,
  first_touch_strategy text,
  source_review_required text,
  trigger_event text,
  post_or_message_url text,
  lead_circumstances text,
  contact_path text,
  phone_confidence text,
  email_confidence text,
  enrichment_notes text,
  inserted_at timestamptz not null default now()
);

create table if not exists public.call_desk_activity (
  activity_id bigint generated by default as identity primary key,
  lead_id bigint not null references public.lead_master(lead_id) on delete cascade,
  activity_date timestamptz,
  channel text,
  activity_type text,
  sequence_name text,
  outcome text,
  owner text,
  notes text,
  inserted_at timestamptz not null default now()
);

create table if not exists public.lead_product_proposal (
  proposal_id bigint generated by default as identity primary key,
  lead_id bigint not null references public.lead_master(lead_id) on delete cascade,
  proposal_date timestamptz,
  product_line text,
  product_interest text,
  policy_type text,
  proposal_source text,
  owner text,
  proposal_status text,
  notes text,
  inserted_at timestamptz not null default now()
);

create table if not exists public.appointment (
  appointment_id bigint generated by default as identity primary key,
  lead_id bigint not null references public.lead_master(lead_id) on delete cascade,
  booking_date timestamptz,
  booking_status text,
  show_status text,
  appointment_type text,
  owner text,
  inserted_at timestamptz not null default now()
);

create table if not exists public.policy_closeout (
  closeout_id bigint generated by default as identity primary key,
  lead_id bigint not null references public.lead_master(lead_id) on delete cascade,
  quote_date timestamptz,
  close_date timestamptz,
  policy_type text,
  policy_status text,
  annual_premium numeric,
  commission_revenue numeric,
  owner text,
  closeout_status text,
  inserted_at timestamptz not null default now()
);

create table if not exists public.lifecycle_event (
  lifecycle_event_id bigint generated by default as identity primary key,
  lead_id bigint not null references public.lead_master(lead_id) on delete cascade,
  event_timestamp timestamptz,
  event_stage text not null,
  event_type text,
  source_table text,
  source_row_id bigint,
  details_json jsonb,
  inserted_at timestamptz not null default now()
);

create table if not exists public.carrier_document (
  carrier_document_id bigint generated by default as identity primary key,
  document_id text unique not null,
  carrier text,
  document_type text,
  title text not null,
  source_url text not null,
  source_type text,
  status text not null default 'pending_review',
  priority text not null default 'normal',
  last_reviewed timestamptz,
  owner text,
  notes text,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_carrier_config (
  id bigint generated by default as identity primary key,
  carrier_name text not null unique,
  writing_number text,
  portal_url text,
  support_phone text
);

create table if not exists public.content_post (
  id bigint generated by default as identity primary key,
  post_id text,
  week_number integer,
  day integer,
  post_date date,
  post_time text,
  scheduled_for timestamptz,
  platforms_json jsonb not null default '[]'::jsonb,
  post_type text,
  topic text,
  hook text,
  caption text,
  reel_script text,
  visual_prompt text,
  canva_design_link text,
  asset_filename text,
  cta text,
  hashtags_text text,
  status text not null default 'draft',
  design_status text not null default 'not_started',
  locked_by uuid references auth.users(id) on delete set null,
  locked_at timestamptz,
  source_file text,
  scheduler_external_id text,
  last_publish_error text,
  created_by text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id, post_date)
);

create table if not exists public.content_revision (
  id bigint generated by default as identity primary key,
  content_post_id bigint not null references public.content_post(id) on delete cascade,
  revision_number integer not null default 1,
  changed_by text,
  change_note text,
  snapshot_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.content_approval (
  id bigint generated by default as identity primary key,
  content_post_id bigint not null references public.content_post(id) on delete cascade,
  decision text not null,
  note text,
  actor text,
  created_at timestamptz not null default now()
);

create table if not exists public.content_publish_job (
  id bigint generated by default as identity primary key,
  content_post_id bigint not null references public.content_post(id) on delete cascade,
  scheduler text not null default 'buffer_postiz',
  request_json jsonb,
  response_json jsonb,
  status text not null default 'queued',
  error_message text,
  run_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_lead_master_email on public.lead_master (email);
create index if not exists idx_lead_master_phone on public.lead_master (mobile_phone);
create index if not exists idx_lead_master_name on public.lead_master (full_name);
create index if not exists idx_lead_master_pipeline_status on public.lead_master (pipeline_status);
create index if not exists idx_lead_master_next_appointment_time on public.lead_master (next_appointment_time);
create index if not exists idx_lead_master_last_opened_at on public.lead_master (last_opened_at);
create index if not exists idx_lena_source_profile_lead on public.lena_source_profile (lead_id);
create index if not exists idx_call_desk_activity_lead_date on public.call_desk_activity (lead_id, activity_date);
create index if not exists idx_product_proposal_lead_date on public.lead_product_proposal (lead_id, proposal_date);
create index if not exists idx_appointment_lead_date on public.appointment (lead_id, booking_date);
create index if not exists idx_policy_closeout_lead_date on public.policy_closeout (lead_id, close_date);
create index if not exists idx_lifecycle_event_lead_date on public.lifecycle_event (lead_id, event_timestamp);
create index if not exists idx_carrier_document_status on public.carrier_document (status, priority);
create index if not exists idx_carrier_document_carrier on public.carrier_document (carrier);
create index if not exists idx_agent_carrier_config_name on public.agent_carrier_config (carrier_name);
create index if not exists idx_content_post_status_schedule on public.content_post (status, scheduled_for);
create index if not exists idx_content_post_design_status on public.content_post (design_status);
create index if not exists idx_content_post_locked_by on public.content_post (locked_by, locked_at);
create index if not exists idx_content_revision_post on public.content_revision (content_post_id, revision_number);
create index if not exists idx_content_publish_job_post on public.content_publish_job (content_post_id, run_at);

drop trigger if exists trg_lead_master_touch_updated_at on public.lead_master;
create trigger trg_lead_master_touch_updated_at
before update on public.lead_master
for each row execute function public.touch_updated_at();

drop trigger if exists trg_carrier_document_touch_updated_at on public.carrier_document;
create trigger trg_carrier_document_touch_updated_at
before update on public.carrier_document
for each row execute function public.touch_updated_at();

drop trigger if exists trg_content_post_touch_updated_at on public.content_post;
create trigger trg_content_post_touch_updated_at
before update on public.content_post
for each row execute function public.touch_updated_at();

drop trigger if exists trg_app_user_profile_touch_updated_at on public.app_user_profile;
create trigger trg_app_user_profile_touch_updated_at
before update on public.app_user_profile
for each row execute function public.touch_updated_at();

alter table public.app_user_profile enable row level security;
alter table public.lead_master enable row level security;
alter table public.lena_source_profile enable row level security;
alter table public.call_desk_activity enable row level security;
alter table public.lead_product_proposal enable row level security;
alter table public.appointment enable row level security;
alter table public.policy_closeout enable row level security;
alter table public.lifecycle_event enable row level security;
alter table public.carrier_document enable row level security;
alter table public.agent_carrier_config enable row level security;
alter table public.content_post enable row level security;
alter table public.content_revision enable row level security;
alter table public.content_approval enable row level security;
alter table public.content_publish_job enable row level security;

drop policy if exists "admin profile read own" on public.app_user_profile;
create policy "admin profile read own"
on public.app_user_profile
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "admin profile update own" on public.app_user_profile;
create policy "admin profile update own"
on public.app_user_profile
for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "admin full lead access" on public.lead_master;
create policy "admin full lead access"
on public.lead_master
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full lena source access" on public.lena_source_profile;
create policy "admin full lena source access"
on public.lena_source_profile
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full call desk access" on public.call_desk_activity;
create policy "admin full call desk access"
on public.call_desk_activity
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full proposal access" on public.lead_product_proposal;
create policy "admin full proposal access"
on public.lead_product_proposal
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full appointment access" on public.appointment;
create policy "admin full appointment access"
on public.appointment
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full closeout access" on public.policy_closeout;
create policy "admin full closeout access"
on public.policy_closeout
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full lifecycle access" on public.lifecycle_event;
create policy "admin full lifecycle access"
on public.lifecycle_event
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full carrier doc access" on public.carrier_document;
create policy "admin full carrier doc access"
on public.carrier_document
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full carrier config access" on public.agent_carrier_config;
create policy "admin full carrier config access"
on public.agent_carrier_config
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin full content post access" on public.content_post;
drop policy if exists "content post read for team" on public.content_post;
create policy "content post read for team"
on public.content_post
for select
to authenticated
using (public.can_edit_content());

create policy "admin full content post access"
on public.content_post
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "content post editor update" on public.content_post;
create policy "content post editor update"
on public.content_post
for update
to authenticated
using (public.can_edit_content())
with check (
  public.can_edit_content()
  and (
    public.can_publish_content()
    or (
      scheduler_external_id is null
      and (status is null or status <> 'published')
    )
  )
);

drop policy if exists "content post editor insert" on public.content_post;
create policy "content post editor insert"
on public.content_post
for insert
to authenticated
with check (public.can_edit_content());

drop policy if exists "admin full content revision access" on public.content_revision;
drop policy if exists "content revision read for team" on public.content_revision;
create policy "content revision read for team"
on public.content_revision
for select
to authenticated
using (public.can_edit_content());

create policy "admin full content revision access"
on public.content_revision
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "content revision insert for team" on public.content_revision;
create policy "content revision insert for team"
on public.content_revision
for insert
to authenticated
with check (public.can_edit_content());

drop policy if exists "admin full content approval access" on public.content_approval;
drop policy if exists "content approval read for team" on public.content_approval;
create policy "content approval read for team"
on public.content_approval
for select
to authenticated
using (public.can_edit_content());

create policy "admin full content approval access"
on public.content_approval
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "content approval insert for approver" on public.content_approval;
create policy "content approval insert for approver"
on public.content_approval
for insert
to authenticated
with check (public.can_approve_content());

drop policy if exists "admin full content publish access" on public.content_publish_job;
drop policy if exists "content publish read for team" on public.content_publish_job;
create policy "content publish read for team"
on public.content_publish_job
for select
to authenticated
using (public.can_edit_content());

create policy "admin full content publish access"
on public.content_publish_job
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
